Authentication
wolox-training/fc-java pull request #16
Opened 2018-12-28 18:07 UTC by facucompe

## Summary

- Authentication for some endpoints

## Trello Card
https://trello.com/c/Xow23gXJ/30-integrar-spring-security

2019-01-03 16:27 UTC, zeminlu requested changes
Looks great!
Only one thing missing... password should be updated in a sepparate endpoint. It's the last line of the card description ;)
You should never update password on the common update endpoint you have here, but rather in a sepparate one.

2019-01-08 06:15 UTC, zeminlu approved these changes

2019-01-08 13:10 UTC, merged

2019-08-19 04:55 UTC, IgnOliveto reviewed
Some minor changes

2019-08-19 04:55 UTC, IgnOliveto commented on src/main/java/wolox/training/security/CustomAuthenticationProvider.java
> +            throw new BadCredentialsException("Invalid user or password");
Please add this error message to the  error message class.

2019-08-19 04:55 UTC, IgnOliveto commented on src/main/java/wolox/training/repositories/UserRepository.java
> +<<<<<<< HEAD
Please remove this merge conflict markers